name: Run Backup

on:
  push:
    branches: master
#  schedule:
#    - cron: 37 2 * * *

jobs:
  deploy:
    name: Run

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup credentials
        run: echo "${{ secrets.CREDENTIALS_JSON }}" > credentials.json
      - name: Debug
        run: cat credentials.json
      - name: Run
        run: python main.py
